name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Build and Deploy
        uses: helaili/jekyll-action@2.2.0
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
        with:
          target_branch: "gh-pages"
